package com.eco.virtuRun.ui.theme

import android.annotation.SuppressLint
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import com.google.android.material.color.utilities.Hct

val md_theme_light_primary = Color(0xFF4D6700)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC2F347)
val md_theme_light_onPrimaryContainer = Color(0xFF151F00)
val md_theme_light_secondary = Color(0xFF7D5700)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDEAA)
val md_theme_light_onSecondaryContainer = Color(0xFF271900)
val md_theme_light_tertiary = Color(0xFF006A60)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF74F8E5)
val md_theme_light_onTertiaryContainer = Color(0xFF00201C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFCF4)
val md_theme_light_onBackground = Color(0xFF1B1C17)
val md_theme_light_surface = Color(0xFFFEFCF4)
val md_theme_light_onSurface = Color(0xFF1B1C17)
val md_theme_light_surfaceVariant = Color(0xFFE2E4D4)
val md_theme_light_onSurfaceVariant = Color(0xFF45483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFF2F1E9)
val md_theme_light_inverseSurface = Color(0xFF30312C)
val md_theme_light_inversePrimary = Color(0xFFA7D629)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4D6700)
val md_theme_light_outlineVariant = Color(0xFFC6C8B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA7D629)
val md_theme_dark_onPrimary = Color(0xFF263500)
val md_theme_dark_primaryContainer = Color(0xFF394D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFC2F347)
val md_theme_dark_secondary = Color(0xFFF9BC49)
val md_theme_dark_onSecondary = Color(0xFF422C00)
val md_theme_dark_secondaryContainer = Color(0xFF5F4100)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDEAA)
val md_theme_dark_tertiary = Color(0xFF53DBC9)
val md_theme_dark_onTertiary = Color(0xFF003731)
val md_theme_dark_tertiaryContainer = Color(0xFF005048)
val md_theme_dark_onTertiaryContainer = Color(0xFF74F8E5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1C17)
val md_theme_dark_onBackground = Color(0xFFE4E3DB)
val md_theme_dark_surface = Color(0xFF1B1C17)
val md_theme_dark_onSurface = Color(0xFFE4E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF45483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C8B8)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1C17)
val md_theme_dark_inverseSurface = Color(0xFFE4E3DB)
val md_theme_dark_inversePrimary = Color(0xFF4D6700)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA7D629)
val md_theme_dark_outlineVariant = Color(0xFF45483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFA7D629)

val LightPrimary = Color(0xFF000000)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDDAE)
val LightOnPrimaryContainer = Color(0xFF2A1800)
val LightSecondary = Color(0xFF6F5B40)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFADEBC)
val LightOnSecondaryContainer = Color(0xFF271904)
val LightTertiary = Color(0xFF516440)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3EABC)
val LightOnTertiaryContainer = Color(0xFF102004)
val LightError = Color(0xFFBA1B1B)
val LightErrorContainer = Color(0xFFFFDAD4)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410001)
val LightBackground = Color(0xFFFCFCFC)
val LightOnBackground = Color(0xFF1F1B16)
val LightSurface = Color(0xFFFCFCFC)
val LightOnSurface = Color(0xFF1F1B16)
val LightSurfaceVariant = Color(0xFFF0E0CF)
val LightOnSurfaceVariant = Color(0xFF4F4539)
val LightOutline = Color(0xFF817567)
val LightInverseOnSurface = Color(0xFFF9EFE6)
val LightInverseSurface = Color(0xFF34302A)
val LightPrimaryInverse = Color(0xFFFFB945)

val DarkPrimary = Color(0xFFFFFFFF)
val DarkOnPrimary = Color(0xFF452B00)
val DarkPrimaryContainer = Color(0xFF624000)
val DarkOnPrimaryContainer = Color(0xFFFFDDAE)
val DarkSecondary = Color(0xFFDDC3A2)
val DarkOnSecondary = Color(0xFF3E2E16)
val DarkSecondaryContainer = Color(0xFF56442B)
val DarkOnSecondaryContainer = Color(0xFFFADEBC)
val DarkTertiary = Color(0xFFB8CEA2)
val DarkOnTertiary = Color(0xFF243516)
val DarkTertiaryContainer = Color(0xFF3A4C2B)
val DarkOnTertiaryContainer = Color(0xFFD3EABC)
val DarkError = Color(0xFFFFB4A9)
val DarkErrorContainer = Color(0xFF930006)
val DarkOnError = Color(0xFF680003)
val DarkOnErrorContainer = Color(0xFFFFDAD4)
val DarkBackground = Color(0xFF1F1B16)
val DarkOnBackground = Color(0xFFEAE1D9)
val DarkSurface = Color(0xFF1F1B16)
val DarkOnSurface = Color(0xFFEAE1D9)
val DarkSurfaceVariant = Color(0xFF4F4539)
val DarkOnSurfaceVariant = Color(0xFFD3C4B4)
val DarkOutline = Color(0xFF9C8F80)
val DarkInverseOnSurface = Color(0xFF32281A)
val DarkInverseSurface = Color(0xFFEAE1D9)
val DarkPrimaryInverse = Color(0xFF624000)

val AppGray = Color(0xC058554D )
val AppLightGray = Color(0xFFBDB6A3 )
val AppBlue = Color(0xB0006068 )
//val AppGreen = Color(0xD0C0CA33 )
val AppLime = Color(0xD0CDDC39)
val AppLightGreen = Color(0xD08BC34A)
val AppGreen = Color(0xD0A7D629)
val AppRed = Color(0xB0CC3F20)
val AppOrange = Color(0xC0CC6C20)
val AppYellow = Color(0xD0E8D404 )
val AppOlive = Color(0xD06B7C03)
val AppIceBlue = Color(0xB0A2D2DF)
val AppBlueGray = Color(0xA07C97AB)
//val AppLightGray = Color(0xA0959288)

@SuppressLint("RestrictedApi")
fun setTone(color: Color, tone: Double): Color {
    val hct: Hct = Hct.fromInt(color.toArgb())
    hct.tone = tone
    return Color(hct.toInt())
}
